/**
 * Regenerates src/ephemeris/seeds.json from JPL Horizons.
 *
 * The seed file holds 55 state vectors (5 bodies x 11 epochs) that nothing in
 * the codebase can derive -- without this script they are unreproducible magic
 * numbers. Run it to refresh against a newer JPL orbit solution, to add an
 * epoch, or to verify the committed file was not hand-edited.
 *
 *   bun run scripts/pull-seeds.ts            # print to stdout, diff yourself
 *   bun run scripts/pull-seeds.ts --write    # overwrite seeds.json
 *
 * Epochs every 20 years keep the integration distance under ~10 years for any
 * date in the supported 1900-2100 range. Integrating from J2000 alone made a
 * 1900 chart with asteroids take 4.7 s; this brings the worst case to ~450 ms
 * and, because a shorter integration drifts less, is slightly more accurate.
 *
 * Vectors are heliocentric (CENTER=500@10) in the equatorial J2000 frame
 * (REF_PLANE=FRAME) in AU and AU/day -- exactly what astronomy-engine's
 * StateVector expects. Do not switch REF_PLANE to ECLIPTIC: the simulator
 * takes EQJ, and the mismatch would be silent.
 */
const HORIZONS_ID: Record<string, string> = {
  Chiron: '2060', Ceres: '1;', Pallas: '2;', Juno: '3;', Vesta: '4;',
};
const EPOCHS = Array.from({ length: 11 }, (_, i) => 1900 + i * 20);

interface Vec { x: number; y: number; z: number; vx: number; vy: number; vz: number }

async function pull(command: string, year: number): Promise<Vec> {
  const q = new URLSearchParams({
    format: 'text', COMMAND: command, OBJ_DATA: 'NO', EPHEM_TYPE: 'VECTORS',
    CENTER: '500@10', REF_PLANE: 'FRAME', VEC_TABLE: '2', OUT_UNITS: 'AU-D',
    START_TIME: `${year}-01-01`, STOP_TIME: `${year}-01-02`, STEP_SIZE: '1d',
  });
  const txt = await (await fetch(`https://ssd.jpl.nasa.gov/api/horizons.api?${q}`)).text();
  const block = txt.split('$$SOE')[1];
  if (!block) throw new Error(`Horizons returned no vectors for ${command} @ ${year}`);
  const nums = (line: string) => line.trim().split(/\s+/)
    .filter((t) => /^-?\d/.test(t) || t.startsWith('-')).map(Number).filter(Number.isFinite);
  const lines = block.trim().split('\n');
  const pos = nums(lines[1].replace(/[XYZ]\s*=/g, ' '));
  const vel = nums(lines[2].replace(/V[XYZ]\s*=/g, ' '));
  return { x: pos[0], y: pos[1], z: pos[2], vx: vel[0], vy: vel[1], vz: vel[2] };
}

const out: Record<string, unknown> = {
  _comment: 'Generated by scripts/pull-seeds.ts from JPL Horizons. '
    + 'Heliocentric (CENTER=500@10), equatorial J2000 (REF_PLANE=FRAME), AU and AU/day. '
    + 'Do not hand-edit -- rerun the script instead.',
};

for (const [body, id] of Object.entries(HORIZONS_ID)) {
  const perEpoch: Record<string, Vec> = {};
  for (const year of EPOCHS) {
    perEpoch[`${year}-01-01T00:00:00Z`] = await pull(id, year);
    await Bun.sleep(250);   // be polite to a free public API
    console.error(`  ${body} ${year} ok`);
  }
  out[body] = perEpoch;
}

const json = `${JSON.stringify(out, null, 1)}\n`;
if (process.argv.includes('--write')) {
  await Bun.write('src/ephemeris/seeds.json', json);
  console.error('wrote src/ephemeris/seeds.json');
} else {
  console.log(json);
}
